# Generated by Django 2.1.7 on 2019-03-27 13:25

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20190327_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=stdimage.models.StdImageField(blank=True, upload_to='profilepictures/'),
        ),
    ]
