# Generated by Django 2.1.7 on 2019-03-27 15:20

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20190327_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='profilepictures/'),
        ),
    ]
